repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python ./scripts/run_black.py
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: python ./scripts/run_black.py
        language: system
        types: [python]
